-- Neo Music Backend · 초기 스키마 (PostgreSQL)
--
-- 그동안 스키마를 ddl-auto 에 맡겼더니, docs/DATA_MODEL.md 가 명시한
-- 인덱스와 유니크 제약이 실제 DB 에는 하나도 만들어지지 않고 있었다.
-- (델타 동기화의 last_modified_version 조회가 매번 풀스캔)
-- 스키마를 코드로 옮기면서 문서가 약속한 제약을 함께 복원한다.
--
-- 이후 스키마 변경은 이 파일을 고치지 말고 V2, V3... 를 새로 추가할 것.

-- ─────────────────────────────────────────────
-- 곡 (애그리거트 루트)
-- ─────────────────────────────────────────────
CREATE TABLE song (
    id                    varchar(64)  NOT NULL,
    title                 varchar(255) NOT NULL,
    artist                varchar(255) NOT NULL,
    cover_key             varchar(255),
    display_order         integer      NOT NULL,
    last_modified_version bigint       NOT NULL,
    is_deleted            boolean      NOT NULL,
    created_at            timestamp(6) with time zone NOT NULL,
    updated_at            timestamp(6) with time zone NOT NULL,
    CONSTRAINT pk_song PRIMARY KEY (id)
);

-- 델타 동기화(`WHERE last_modified_version > ?` 정렬·범위 조회)의 핵심 인덱스.
-- 이 API 에서 가장 자주 도는 쿼리라 없으면 곡이 늘수록 그대로 느려진다.
CREATE INDEX idx_song_last_modified_version ON song (last_modified_version);

-- 첫 동기화는 삭제되지 않은 곡만 버전 순으로 훑는다.
CREATE INDEX idx_song_active_version ON song (is_deleted, last_modified_version);

-- ─────────────────────────────────────────────
-- 언어별 오디오 트랙
-- ─────────────────────────────────────────────
CREATE TABLE track (
    id          bigint       GENERATED BY DEFAULT AS IDENTITY,
    song_id     varchar(64),
    lang        varchar(8)   NOT NULL,
    label       varchar(255) NOT NULL,
    audio_key   varchar(255) NOT NULL,
    duration_ms integer      NOT NULL,
    bytes       bigint       NOT NULL,
    checksum    varchar(255) NOT NULL,
    CONSTRAINT pk_track PRIMARY KEY (id),
    CONSTRAINT fk_track_song FOREIGN KEY (song_id) REFERENCES song (id)
);

CREATE INDEX idx_track_song ON track (song_id);

-- ─────────────────────────────────────────────
-- 언어별 가사 (1차: 이미지, 2차: 구조화 텍스트)
-- ─────────────────────────────────────────────
CREATE TABLE lyric (
    id      bigint      GENERATED BY DEFAULT AS IDENTITY,
    song_id varchar(64),
    lang    varchar(8)  NOT NULL,
    type    varchar(16) NOT NULL,
    CONSTRAINT pk_lyric PRIMARY KEY (id),
    CONSTRAINT fk_lyric_song FOREIGN KEY (song_id) REFERENCES song (id),
    CONSTRAINT ck_lyric_type CHECK (type IN ('IMAGE', 'TEXT'))
);

CREATE INDEX idx_lyric_song ON lyric (song_id);

-- 가사 이미지 (여러 페이지, 순서 보존)
CREATE TABLE lyric_image (
    lyric_id  bigint       NOT NULL,
    image_key varchar(255) NOT NULL,
    idx       integer      NOT NULL,
    CONSTRAINT pk_lyric_image PRIMARY KEY (lyric_id, idx),
    CONSTRAINT fk_lyric_image_lyric FOREIGN KEY (lyric_id) REFERENCES lyric (id)
);

-- ─────────────────────────────────────────────
-- 전역 카탈로그 버전 (단일 행)
-- ─────────────────────────────────────────────
CREATE TABLE catalog_version (
    id      integer NOT NULL,
    version bigint  NOT NULL,
    CONSTRAINT pk_catalog_version PRIMARY KEY (id)
);

-- ─────────────────────────────────────────────
-- 회원
-- ─────────────────────────────────────────────
CREATE TABLE member (
    id              bigint       GENERATED BY DEFAULT AS IDENTITY,
    nickname        varchar(20)  NOT NULL,
    password_hash   varchar(255) NOT NULL,
    role            varchar(16)  NOT NULL,
    failed_attempts integer      NOT NULL,
    locked_until    timestamp(6) with time zone,
    created_at      timestamp(6) with time zone NOT NULL,
    updated_at      timestamp(6) with time zone NOT NULL,
    CONSTRAINT pk_member PRIMARY KEY (id),
    CONSTRAINT uk_member_nickname UNIQUE (nickname),
    CONSTRAINT ck_member_role CHECK (role IN ('USER', 'ADMIN'))
);

-- ─────────────────────────────────────────────
-- 플레이리스트
-- ─────────────────────────────────────────────
CREATE TABLE playlist (
    id         bigint      GENERATED BY DEFAULT AS IDENTITY,
    owner_id   bigint      NOT NULL,
    name       varchar(50) NOT NULL,
    version    bigint      NOT NULL,   -- 낙관적 락(@Version)
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT pk_playlist PRIMARY KEY (id)
);

-- "내 플레이리스트 목록" 조회용
CREATE INDEX idx_playlist_owner ON playlist (owner_id);

CREATE TABLE playlist_song (
    playlist_id bigint       NOT NULL,
    song_id     varchar(255) NOT NULL,
    position    integer      NOT NULL,
    CONSTRAINT pk_playlist_song PRIMARY KEY (playlist_id, position),
    CONSTRAINT fk_playlist_song_playlist FOREIGN KEY (playlist_id) REFERENCES playlist (id)
);
